apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/kratos-deployment.yaml
  - k8s/kratos-ingress.yaml

configMapGenerator:
  - name: kratos-configmap
    files:
      - kratos.yaml
      - identity.schema.json